### ISSUE TITLE
Incorrect concatenation of extra markers lead to incorrect precedence

### ISSUE THREAD

**Issue by frostming** [FFY00/python-pyproject-metadata#82]
If I have this optional dependencies:

```toml
[project.optional-dependencies]
d = [
  "aiohttp>=3.7.4; sys_platform != 'win32' or implementation_name != 'pypy'",
]
```

It will generate core metadata as follows:

```
Requires-Dist: aiohttp>=3.7.4; sys_platform != "win32" or implementation_name != "pypy" and extra == "d"
```

While the expected result with correct precedence is:

```
Requires-Dist: aiohttp>=3.7.4; (sys_platform != "win32" or implementation_name != "pypy") and extra == "d"
```

Reported by https://github.com/pdm-project/pdm-backend/issues/210

I am willing to submit a PR for this.
